# Site settings
name: Brighton Tafadzwa Chirima
email: chirimab56@gmail.com
#canonical_url: https://
keywords: "Software Engineer, Python, Java, IOT, Data Science, Startups, PHP, JavaScript,Parallel Programming"
skills: "Full Stack Developer"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: facebook
    url: https://www.facebook.com/tafadzwa.chirima.5

  -title: LinkedIn
     url: https://www.linkedin.com/in/brighton-tafadzwa-chirima-a2a34a146/

  - title: twitter
    url: https://twitter.com/BrightonChirima
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 9370DB
  primary-rgb: "58, 44, 86"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
